# Generated by Django 4.1.4 on 2022-12-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_arrond', models.IntegerField()),
                ('lib_arrond', models.CharField(max_length=255)),
                ('id_com', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_com', models.IntegerField()),
                ('lib_com', models.CharField(max_length=255)),
                ('id_dep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dep', models.IntegerField()),
                ('lib_dep', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quart', models.IntegerField()),
                ('lib_quart', models.CharField(max_length=255)),
                ('id_arrond', models.IntegerField()),
            ],
        ),
    ]
